In [22]:
# Dependencies
import pandas as pd

In [30]:
#Extract Licensed Drivers by state (DL) csv into pandas DF for year 2016
DL_DF = pd.read_csv("Resources/DL.csv", usecols=[0,68])
DL_DF

             STATE        2016
0          Alabama   3,943,082
1           Alaska     534,585
2          Arizona   5,082,305
3         Arkansas   2,391,103
4       California  26,199,436
5         Colorado   4,066,580
6      Connecticut   2,611,007
7         Delaware     756,328
8    Dist. of Col.     489,831
9          Florida  14,675,160
10         Georgia   6,975,900
11          Hawaii     931,703
12           Idaho   1,160,922
13        Illinois   8,514,644
14         Indiana   4,553,259
15            Iowa   2,245,640
16          Kansas   2,030,025
17        Kentucky   3,031,447
18       Louisiana   3,395,095
19           Maine   1,021,332
20        Maryland   4,264,875
21   Massachusetts   5,040,662
22        Michigan   7,074,674
23       Minnesota   3,377,910
24     Mississippi   2,018,862
25        Missouri   4,249,579
26         Montana     797,145
27        Nebraska   1,404,479
28          Nevada   1,872,376
29   New Hampshire   1,096,234
30      New Jersey   6,238,436
31      New Mexico   1,521,785
32        New York  11,947,568
33  North Carolina   7,267,042
34    North Dakota     555,935
35            Ohio   7,974,951
36        Oklahoma   2,498,178
37          Oregon   2,855,746
38    Pennsylvania   8,996,815
39    Rhode Island     753,143
40  South Carolina   3,746,681
41    South Dakota     622,663
42       Tennessee   5,197,904
43           Texas  15,879,876
44            Utah   1,960,366
45         Vermont     553,670
46        Virginia   5,912,048
47      Washington   5,635,715
48   West Virginia   1,159,348
49       Wisconsin   4,206,770
50         Wyoming     421,098

In [29]:
# clean Licensed Drivers by state (DL)
DL_DF_Clean = DL_DF.rename(columns={'2016':'Licenced_Driver(2016)'})
DL_DF_Clean

             STATE Licenced_Driver(2016)
0          Alabama             3,943,082
1           Alaska               534,585
2          Arizona             5,082,305
3         Arkansas             2,391,103
4       California            26,199,436
5         Colorado             4,066,580
6      Connecticut             2,611,007
7         Delaware               756,328
8    Dist. of Col.               489,831
9          Florida            14,675,160
10         Georgia             6,975,900
11          Hawaii               931,703
12           Idaho             1,160,922
13        Illinois             8,514,644
14         Indiana             4,553,259
15            Iowa             2,245,640
16          Kansas             2,030,025
17        Kentucky             3,031,447
18       Louisiana             3,395,095
19           Maine             1,021,332
20        Maryland             4,264,875
21   Massachusetts             5,040,662
22        Michigan             7,074,674
23       Minnesota             3,377,910
24     Mississippi             2,018,862
25        Missouri             4,249,579
26         Montana               797,145
27        Nebraska             1,404,479
28          Nevada             1,872,376
29   New Hampshire             1,096,234
30      New Jersey             6,238,436
31      New Mexico             1,521,785
32        New York            11,947,568
33  North Carolina             7,267,042
34    North Dakota               555,935
35            Ohio             7,974,951
36        Oklahoma             2,498,178
37          Oregon             2,855,746
38    Pennsylvania             8,996,815
39    Rhode Island               753,143
40  South Carolina             3,746,681
41    South Dakota               622,663
42       Tennessee             5,197,904
43           Texas            15,879,876
44            Utah             1,960,366
45         Vermont               553,670
46        Virginia             5,912,048
47      Washington             5,635,715
48   West Virginia             1,159,348
49       Wisconsin             4,206,770
50         Wyoming               421,098

In [27]:
#Extract Registered Motor Vehicles(RMV) csv into pandas DF
RMV_DF = pd.read_csv("Resources/RMV.csv", usecols=[0,15], skiprows=4)
RMV_DF

        Unnamed: 0 Unnamed: 15
0          Alabama   5,468,301
1          Alaska      794,614
2          Arizona   5,786,891
3         Arkansas   2,808,138
4      California   30,221,033
5        Colorado    5,116,341
6     Connecticut    2,841,842
7        Delaware    1,003,840
8   Dist. of Col.      337,100
9         Florida   16,600,317
10        Georgia    8,239,779
11          Hawaii   1,231,728
12           Idaho   1,842,245
13       Illinois   10,277,182
14         Indiana   6,140,530
15           Iowa    3,676,290
16          Kansas   2,649,736
17        Kentucky   4,224,788
18       Louisiana   3,904,962
19          Maine    1,107,674
20        Maryland   4,178,873
21   Massachusetts   5,069,559
22        Michigan   8,332,895
23      Minnesota    5,358,317
24    Mississippi    2,067,222
25        Missouri   5,684,525
26        Montana    1,794,732
27        Nebraska   1,951,766
28         Nevada    2,398,659
29   New Hampshire   1,322,682
30     New Jersey    5,940,997
31      New Mexico   1,823,961
32       New York   11,122,392
33  North Carolina   8,270,643
34    North Dakota     894,954
35            Ohio  10,686,057
36      Oklahoma     3,737,405
37         Oregon    3,811,706
38    Pennsylvania  10,748,822
39   Rhode Island      876,228
40  South Carolina   4,324,423
41   South Dakota    1,246,359
42      Tennessee    5,709,923
43          Texas   21,766,166
44            Utah   2,317,282
45         Vermont     615,950
46        Virginia   7,301,081
47     Washington    7,047,689
48   West Virginia   1,704,825
49      Wisconsin    5,564,429
50        Wyoming      855,230

In [28]:
# clean egistered Motor Veicheles(RMV)
RMV_DF_Clean = RMV_DF.rename(columns={'Unnamed: 0':'STATE','Unnamed: 15':'Registered_Vehicles(2016)'})
RMV_DF_Clean

             STATE Registered_Vehicles(2016)
0          Alabama                 5,468,301
1          Alaska                    794,614
2          Arizona                 5,786,891
3         Arkansas                 2,808,138
4      California                 30,221,033
5        Colorado                  5,116,341
6     Connecticut                  2,841,842
7        Delaware                  1,003,840
8   Dist. of Col.                    337,100
9         Florida                 16,600,317
10        Georgia                  8,239,779
11          Hawaii                 1,231,728
12           Idaho                 1,842,245
13       Illinois                 10,277,182
14         Indiana                 6,140,530
15           Iowa                  3,676,290
16          Kansas                 2,649,736
17        Kentucky                 4,224,788
18       Louisiana                 3,904,962
19          Maine                  1,107,674
20        Maryland                 4,178,873
21   Massachusetts                 5,069,559
22        Michigan                 8,332,895
23      Minnesota                  5,358,317
24    Mississippi                  2,067,222
25        Missouri                 5,684,525
26        Montana                  1,794,732
27        Nebraska                 1,951,766
28         Nevada                  2,398,659
29   New Hampshire                 1,322,682
30     New Jersey                  5,940,997
31      New Mexico                 1,823,961
32       New York                 11,122,392
33  North Carolina                 8,270,643
34    North Dakota                   894,954
35            Ohio                10,686,057
36      Oklahoma                   3,737,405
37         Oregon                  3,811,706
38    Pennsylvania                10,748,822
39   Rhode Island                    876,228
40  South Carolina                 4,324,423
41   South Dakota                  1,246,359
42      Tennessee                  5,709,923
43          Texas                 21,766,166
44            Utah                 2,317,282
45         Vermont                   615,950
46        Virginia                 7,301,081
47     Washington                  7,047,689
48   West Virginia                 1,704,825
49      Wisconsin                  5,564,429
50        Wyoming                    855,230

In [ ]:
# us_state_abbrev = {
#    'Alabama': 'AL',
#    'Alaska': 'AK',
#    'Arizona': 'AZ',
#    'Arkansas': 'AR',
#    'California': 'CA',
#    'Colorado': 'CO',
#    'Connecticut': 'CT',
#    'Delaware': 'DE',
#    'Florida': 'FL',
#    'Georgia': 'GA',
#    'Hawaii': 'HI',
#    'Idaho': 'ID',
#    'Illinois': 'IL',
#    'Indiana': 'IN',
#    'Iowa': 'IA',
#    'Kansas': 'KS',
#    'Kentucky': 'KY',
#    'Louisiana': 'LA',
#    'Maine': 'ME',
#    'Maryland': 'MD',
#    'Massachusetts': 'MA',
#    'Michigan': 'MI',
#    'Minnesota': 'MN',
#    'Mississippi': 'MS',
#    'Missouri': 'MO',
#    'Montana': 'MT',
#    'Nebraska': 'NE',
#    'Nevada': 'NV',
#    'New Hampshire': 'NH',
#    'New Jersey': 'NJ',
#    'New Mexico': 'NM',
#    'New York': 'NY',
#    'North Carolina': 'NC',
#    'North Dakota': 'ND',
#    'Ohio': 'OH',
#    'Oklahoma': 'OK',
#    'Oregon': 'OR',
#    'Pennsylvania': 'PA',
#    'Rhode Island': 'RI',
#    'South Carolina': 'SC',
#    'South Dakota': 'SD',
#    'Tennessee': 'TN',
#    'Texas': 'TX',
#    'Utah': 'UT',
#    'Vermont': 'VT',
#    'Virginia': 'VA',
#    'Washington': 'WA',
#    'West Virginia': 'WV',
#    'Wisconsin': 'WI',
#    'Wyoming': 'WY',
# }

# for key, value in us_state_abbrev.items():
#     DL_DF_Clean.loc[DL_DF_Clean['STATE']==key,'STATE'] = value